#
# https://github.com/marketplace/actions/mirror-to-gitlab-and-run-gitlab-ci
#
# https://github.com/mozgbrasil/acid-workspaces/settings/secrets/actions
#
# ğŸ‘‰ï¸ New repository secret:
#
# GITLAB_PASSWORD: Generate here: https://gitlab.com/-/profile/personal_access_tokens
# GITLAB_PROJECT_ID: https://gitlab.com/<namespace>/<repository>/edit

name: ğŸ‘‡ï¸ Mirror and run GitLab CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: ğŸ‘‡ï¸ Run a one-line script
        run: echo Hello, world! xs

      - name: ğŸ‘‡ï¸ Run env
        run: env

      - name: ğŸ‘‡ï¸ Mirror + trigger CI
        uses: SvanBoxel/gitlab-mirror-and-ci-action@master
        with:
          args: "https://gitlab.com/mozgbrasil/acid-workspaces"
        env:
          GITLAB_HOSTNAME: "gitlab.com"
          GITLAB_USERNAME: "svboxel"
          GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
          GITLAB_PROJECT_ID: ${{ secrets.GITLAB_PROJECT_ID }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
